

services:
  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://wallet-db:5432/${DB_NAME:-wallet_db}
       SPRING_DATASOURCE_USERNAME: ${DB_USER:-root}
       SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-root}

#      - SPRING_JPA_HIBERNATE_DDL_AUTO=${DDL_AUTO:-validate}
#      - SPRING_CACHE_TYPE=${CACHE_TYPE:-caffeine}
    depends_on:
      wallet-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  wallet-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_NAME:-wallet_db}
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  wallet-db-data: