spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/wallet_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  cache:  # Настройки кэширования
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s
    cache-names: wallets

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  cache:
    caffeine:
      stats: true